// src/screens/FavoritesManagerScreen.styles.ts
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f2f2f2' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#ffffff',
    elevation: 3,
    justifyContent: 'space-between',
  },
  backText: { fontSize: 36, fontWeight: 'bold', padding: 12 },
  headerTitle: { fontSize: 24, fontWeight: 'bold' },
  addText: { fontSize: 18, fontWeight: '600', color: '#1e88e5' },

  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  emptyText: { fontSize: 20, fontWeight: 'bold', marginBottom: 16 },
  addEmptyButton: {
    backgroundColor: '#1e88e5',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 24,
  },
  addEmptyText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },

  listContent: { padding: 12 },
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    elevation: 2,
  },
  left: { marginRight: 12 },
  avatar: { width: 64, height: 64, borderRadius: 32 },
  avatarPlaceholder: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#e0e0e0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarInitial: { fontSize: 28, fontWeight: 'bold' },
  center: { flex: 1 },
  name: { fontSize: 20, fontWeight: 'bold' },
  phone: { fontSize: 16, marginTop: 2, color: '#666' },
  rightActions: { flexDirection: 'row', gap: 8 },
  callButton: {
    backgroundColor: '#1e88e5',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 24,
  },
  callText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  removeButton: {
    backgroundColor: '#ef5350',
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeText: { color: '#fff', fontSize: 20, fontWeight: 'bold' },

  // Modal de adicionar
  modalContainer: { flex: 1, backgroundColor: '#f2f2f2' },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#ffffff',
    elevation: 3,
  },
  modalTitle: { fontSize: 24, fontWeight: 'bold', marginLeft: 16 },
  searchInput: {
    backgroundColor: '#030303',
    color: '#ffffff',
    padding: 16,
    fontSize: 16,
    margin: 16,
    borderRadius: 12,
    elevation: 1,
  },
  addList: { flex: 1 },
  addContactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    padding: 16,
    marginHorizontal: 16,
    marginVertical: 4,
    borderRadius: 12,
    elevation: 1,
  },
  addContactLeft: { marginRight: 12 },
  addAvatar: { width: 56, height: 56, borderRadius: 28 },
  addAvatarPlaceholder: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#e0e0e0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addAvatarInitial: { fontSize: 24, fontWeight: 'bold' },
  addContactInfo: { flex: 1 },
  addContactName: { fontSize: 18, fontWeight: '600' },
  addContactPhone: { fontSize: 16, color: '#666', marginTop: 2 },
  addStar: { fontSize: 24, color: '#1e88e5' },
});

export default styles;
